import { FarmerBooking, MandiCentre, SlotAvailability } from "@/types/kisanSetu";

export const MOCK_ACTIVE_FARMER_BOOKING: FarmerBooking = {
  tokenNumber: "PB-KHA-024",
  farmerName: "Ramesh Kumar",
  farmerNameHi: "रमेश कुमार",
  farmerPhone: "+91 98765 43210",
  centreName: "Karnal Main Paddy Mandi",
  centreNameHi: "करनाल मुख्य धान मंडी",
  district: "Karnal, Haryana",
  cropType: "Paddy (PR-126)",
  cropTypeHi: "धान (PR-126)",
  estimatedQuantityQuintals: 65,
  bookingDate: "19 Sept 2026",
  slotTime: "10:00 AM – 11:00 AM",
  queuePosition: 8,
  peopleAhead: 7,
  estimatedWaitMinutes: 31,
  currentStatus: "WAITING",
  nextActionEn: "Proceed to Gate #1 with vehicle registration HR-45-B-1024",
  nextActionHi: "वाहन नंबर HR-45-B-1024 के साथ गेट #1 पर पहुंचें",
  vehicleNo: "HR-45-B-1024",
  grossWeightKg: 8450,
  tareWeightKg: 1950,
  netWeightQuintals: 65,
  moisturePercentage: 12.8,
  qualityGrade: "GRADE_A",
  mspRatePerQuintal: 2320,
  totalPaymentAmount: 150800,
  paymentTransactionRef: "UTR-DBT-20260918-9942",
};

export const MOCK_MANDI_CENTRES: MandiCentre[] = [
  {
    id: "mandi-1",
    name: "Karnal Main Grain Procurement Centre",
    nameHi: "करनाल मुख्य अनाज खरीद केंद्र",
    district: "Karnal",
    distanceKm: 4.2,
    activeCounters: 4,
    status: "NORMAL",
    availableSlotsCount: 42,
  },
  {
    id: "mandi-2",
    name: "Gharaunda Paddy Mandi",
    nameHi: "घरौंडा धान मंडी",
    district: "Karnal",
    distanceKm: 12.8,
    activeCounters: 3,
    status: "BUSY",
    availableSlotsCount: 18,
  },
  {
    id: "mandi-3",
    name: "Assandh Co-operative Mandi",
    nameHi: "असंध सहकारी मंडी",
    district: "Karnal",
    distanceKm: 24.5,
    activeCounters: 2,
    status: "HEAVY_CONGESTION",
    availableSlotsCount: 5,
  },
];

export const MOCK_TIME_SLOTS: SlotAvailability[] = [
  {
    id: "s1",
    timeWindow: "08:00 AM – 09:00 AM",
    availableSlots: 2,
    totalCapacity: 25,
    expectedWaitMin: 45,
    crowdLevel: "High",
  },
  {
    id: "s2",
    timeWindow: "09:00 AM – 10:00 AM",
    availableSlots: 8,
    totalCapacity: 25,
    expectedWaitMin: 35,
    crowdLevel: "Moderate",
  },
  {
    id: "s3",
    timeWindow: "10:00 AM – 11:00 AM",
    availableSlots: 14,
    totalCapacity: 25,
    expectedWaitMin: 20,
    crowdLevel: "Low",
  },
  {
    id: "s4",
    timeWindow: "11:00 AM – 12:00 PM",
    availableSlots: 18,
    totalCapacity: 25,
    expectedWaitMin: 15,
    crowdLevel: "Low",
  },
  {
    id: "s5",
    timeWindow: "02:00 PM – 03:00 PM",
    availableSlots: 22,
    totalCapacity: 25,
    expectedWaitMin: 10,
    crowdLevel: "Low",
  },
];

export const MOCK_OPERATOR_QUEUE: FarmerBooking[] = [
  {
    tokenNumber: "PB-KHA-021",
    farmerName: "Baldev Singh",
    farmerNameHi: "बलदेव सिंह",
    farmerPhone: "+91 98123 45678",
    centreName: "Karnal Main Mandi",
    centreNameHi: "करनाल मुख्य मंडी",
    district: "Karnal",
    cropType: "Paddy",
    cropTypeHi: "धान",
    estimatedQuantityQuintals: 80,
    bookingDate: "19 Sept 2026",
    slotTime: "09:00 AM - 10:00 AM",
    queuePosition: 1,
    peopleAhead: 0,
    estimatedWaitMinutes: 0,
    currentStatus: "WEIGHING",
    nextActionEn: "Gross weight logged (10,400 kg). Recording tare weight.",
    nextActionHi: "सकल वजन दर्ज (10,400 किग्रा)। खाली वजन दर्ज हो रहा है।",
    vehicleNo: "HR-05-AB-8821",
  },
  {
    tokenNumber: "PB-KHA-022",
    farmerName: "Sukhwinder Kaur",
    farmerNameHi: "सुखविंदर कौर",
    farmerPhone: "+91 98234 56789",
    centreName: "Karnal Main Mandi",
    centreNameHi: "करनाल मुख्य मंडी",
    district: "Karnal",
    cropType: "Paddy",
    cropTypeHi: "धान",
    estimatedQuantityQuintals: 45,
    bookingDate: "19 Sept 2026",
    slotTime: "09:00 AM - 10:00 AM",
    queuePosition: 2,
    peopleAhead: 1,
    estimatedWaitMinutes: 5,
    currentStatus: "ARRIVED",
    nextActionEn: "Gate entry completed. Waiting for Weighing Bridge #1.",
    nextActionHi: "गेट प्रवेश पूर्ण। धर्मकांटा #1 के लिए प्रतीक्षा।",
    vehicleNo: "HR-45-C-3310",
  },
  {
    tokenNumber: "PB-KHA-023",
    farmerName: "Gurpreet Singh",
    farmerNameHi: "गुरप्रीत सिंह",
    farmerPhone: "+91 98345 67890",
    centreName: "Karnal Main Mandi",
    centreNameHi: "करनाल मुख्य मंडी",
    district: "Karnal",
    cropType: "Paddy",
    cropTypeHi: "धान",
    estimatedQuantityQuintals: 110,
    bookingDate: "19 Sept 2026",
    slotTime: "10:00 AM - 11:00 AM",
    queuePosition: 3,
    peopleAhead: 2,
    estimatedWaitMinutes: 14,
    currentStatus: "CALLED",
    nextActionEn: "Called to Gate Counter #1",
    nextActionHi: "गेट काउंटर #1 पर बुलाया गया",
    vehicleNo: "HR-45-D-9901",
  },
  {
    tokenNumber: "PB-KHA-024",
    farmerName: "Ramesh Kumar",
    farmerNameHi: "रमेश कुमार",
    farmerPhone: "+91 98765 43210",
    centreName: "Karnal Main Mandi",
    centreNameHi: "करनाल मुख्य मंडी",
    district: "Karnal",
    cropType: "Paddy",
    cropTypeHi: "धान",
    estimatedQuantityQuintals: 65,
    bookingDate: "19 Sept 2026",
    slotTime: "10:00 AM - 11:00 AM",
    queuePosition: 4,
    peopleAhead: 3,
    estimatedWaitMinutes: 22,
    currentStatus: "WAITING",
    nextActionEn: "Awaiting operator call",
    nextActionHi: "ऑपरेटर कॉल की प्रतीक्षा",
    vehicleNo: "HR-45-B-1024",
  },
  {
    tokenNumber: "PB-KHA-025",
    farmerName: "Vikram Sharma",
    farmerNameHi: "विक्रम शर्मा",
    farmerPhone: "+91 98456 78901",
    centreName: "Karnal Main Mandi",
    centreNameHi: "करनाल मुख्य मंडी",
    district: "Karnal",
    cropType: "Paddy",
    cropTypeHi: "धान",
    estimatedQuantityQuintals: 50,
    bookingDate: "19 Sept 2026",
    slotTime: "10:00 AM - 11:00 AM",
    queuePosition: 5,
    peopleAhead: 4,
    estimatedWaitMinutes: 30,
    currentStatus: "WAITING",
    nextActionEn: "Awaiting operator call",
    nextActionHi: "ऑपरेटर कॉल की प्रतीक्षा",
    vehicleNo: "HR-45-E-4412",
  },
];
