import { QueueStatus, StatusConfig } from "@/types/kisanSetu";

export const STATUS_MAP: Record<QueueStatus, StatusConfig> = {
  WAITING: {
    labelEn: "WAITING IN QUEUE",
    labelHi: "कतार में प्रतीक्षारत",
    bgColor: "var(--status-waiting-bg)",
    fgColor: "var(--status-waiting-fg)",
    borderColor: "var(--status-waiting-border)",
    iconName: "Clock",
    descriptionEn: "Your booking is registered. Please await counter call.",
    descriptionHi: "आपका टोकन दर्ज है। काउंटर कॉल की प्रतीक्षा करें।",
  },
  CALLED: {
    labelEn: "CALLED TO COUNTER",
    labelHi: "काउंटर पर बुलाया गया",
    bgColor: "var(--status-called-bg)",
    fgColor: "var(--status-called-fg)",
    borderColor: "var(--status-called-border)",
    iconName: "Megaphone",
    descriptionEn: "Please report immediately to Counter #2 with your tractor.",
    descriptionHi: "कृपया तुरंत अपने वाहन के साथ काउंटर #2 पर पहुंचें।",
  },
  ARRIVED: {
    labelEn: "GATE ENTRY VERIFIED",
    labelHi: "गेट प्रवेश सत्यापित",
    bgColor: "var(--status-arrived-bg)",
    fgColor: "var(--status-arrived-fg)",
    borderColor: "var(--status-arrived-border)",
    iconName: "CheckCircle2",
    descriptionEn: "Vehicle entered mandi gate. Proceed to weighing bridge.",
    descriptionHi: "वाहन मंडी गेट में प्रविष्ट। धर्मकांटा की ओर बढ़ें।",
  },
  WEIGHING: {
    labelEn: "WEIGHING IN PROGRESS",
    labelHi: "तौल जारी है",
    bgColor: "var(--status-weighing-bg)",
    fgColor: "var(--status-weighing-fg)",
    borderColor: "var(--status-weighing-border)",
    iconName: "Scale",
    descriptionEn: "Gross and tare weight being recorded at Bridge Scale #1.",
    descriptionHi: "धर्मकांटा #1 पर सकल एवं खाली वजन दर्ज किया जा रहा है।",
  },
  QUALITY_CHECK: {
    labelEn: "QUALITY CHECK",
    labelHi: "गुणवत्ता जांच",
    bgColor: "var(--status-quality-bg)",
    fgColor: "var(--status-quality-fg)",
    borderColor: "var(--status-quality-border)",
    iconName: "FileCheck",
    descriptionEn: "Moisture content and grain grade inspection under way.",
    descriptionHi: "नमी प्रतिशत एवं अनाज की श्रेणी की जांच की जा रही है।",
  },
  PROCUREMENT_COMPLETED: {
    labelEn: "PROCUREMENT APPROVED",
    labelHi: "खरीद स्वीकृत",
    bgColor: "var(--status-procurement-bg)",
    fgColor: "var(--status-procurement-fg)",
    borderColor: "var(--status-procurement-border)",
    iconName: "Award",
    descriptionEn: "Produce accepted. J-Form receipt generated.",
    descriptionHi: "फसल स्वीकृत। डिजिटल जे-फॉर्म रसीद जारी।",
  },
  PAYMENT_PENDING: {
    labelEn: "PAYMENT PENDING",
    labelHi: "भुगतान लंबित",
    bgColor: "var(--status-payment-pending-bg)",
    fgColor: "var(--status-payment-pending-fg)",
    borderColor: "var(--status-payment-pending-border)",
    iconName: "Hourglass",
    descriptionEn: "Direct Benefit Transfer (DBT) initiated to your bank account.",
    descriptionHi: "डीबीटी (DBT) भुगतान आपके बैंक खाते में भेजा जा रहा है।",
  },
  COMPLETED: {
    labelEn: "PAYMENT COMPLETED",
    labelHi: "भुगतान पूर्ण",
    bgColor: "var(--status-completed-bg)",
    fgColor: "var(--status-completed-fg)",
    borderColor: "var(--status-completed-border)",
    iconName: "BadgeCheck",
    descriptionEn: "MSP payment credited successfully to your Aadhar-linked account.",
    descriptionHi: "एमएसपी (MSP) राशि आपके बैंक खाते में जमा हो चुकी है।",
  },
  CANCELLED: {
    labelEn: "BOOKING CANCELLED",
    labelHi: "टोकन रद्द",
    bgColor: "var(--status-cancelled-bg)",
    fgColor: "var(--status-cancelled-fg)",
    borderColor: "var(--status-cancelled-border)",
    iconName: "AlertTriangle",
    descriptionEn: "This token was voided or produce was rejected.",
    descriptionHi: "यह टोकन रद्द या अस्वीकृत किया गया है।",
  },
};
